export { default as Home } from './Home/Home'
export { default as Profile } from './Profile/Profile'
export {default as ProfileImage} from './Profile/ProfileImage'
export { default as EmergencyContacts } from './EmergencyContacts/EmergencyContacts'
export { default as AddEditContacts } from './EmergencyContacts/AddEditContacts'
export { default as Login } from './Login/Login.js';
export { default as Register } from './Register/Register'
export { default as ForgetPassword } from './ForegtPassword/ForgetPassword'
export { default as VerfiyOtp } from './VerfiyOtp/VerfiyOtp'
export { default as Disclaimer } from './Disclaimer/Disclaimer'
export { default as ResetPassword } from './ResetPassword/ResetPassword'
export { default as TestList } from './Tests/TestList'
export { default as PersonalityTest } from './Tests/PersonalityTest'
export { default as EditProfile } from './EditProfile/EditProfile'
export { default as EmergencyUs } from './EmergencyUs/EmergencyUs'
export { default as Settings } from './Settings/Settings'
export { default as EditPaasword } from './EditPassword/EditPaasword'
export { default as VoiceCode } from './VoiceCode/VoiceCode.tsx'
export { default as AddEditVoicePasscode } from './VoiceCode/AddEditVoicePasscode'
export { default as DateEntry } from './DateEntryDeatils/DateEntry'
export { default as Share } from './Share/Share'
export { default as Help } from './HelpandSupport/Help'
export { default as SafetyGuide } from './SafteyGuide/SafetyGuide'
export { default as Legal } from './Legal/Legal'
export { default as AddDateDetails } from './DateDetails/AddDateDetails'
export { default as DateList } from './DateList/DateList'
export { default as Gallery } from './Gallery/Gallery'
export { default as getStarted } from './GetStarted/GetStarted'
export {default as SafetyResources} from'./SafetyResources/SafetyResources'
export {default as VerifyProfile} from './VerifyProfile/VerifyProfile'
// export {default as contacts} from './Contacts/Contacts'
// export {default as GetConservation} from './Chat/GetConservation/GetConservation'
export{default as GetChat} from './Chat/GetChat/GetChat'
export {default as PracticeMode} from './VoiceCode/PracticeMode'
export {default as EmergencyPasscode} from './VoiceCode/EmergencyPasscode'