import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    // flexWrap: 'wrap'
  },
  header: {
    paddingVertical: '2%',
    marginVertical: '2%',
    marginVertical: '2%',
    // borderBottomWidth:1,
    // borderBottomColor:'grey',
    marginHorizontal: '1%',
  },
  title: {
    fontSize: 22,
    textAlign: 'center',
    color: '#ffff',
    marginHorizontal: '3%',
  },
  reciverMessage: {
    backgroundColor: '#ffff',
    color: 'grey',
    padding: '2%',
    borderWidth: 2,
    alignSelf: 'flex-end',
    width: '60%',
    marginVertical: '0.5%',
    marginHorizontal: '1%',
    borderRadius: 10,
    fontSize: 16,
    fontFamily: 'Rubika',
    elevation: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: 'transparent',
    // backgroundColor: '#ffff',
    borderRadius: 20,
    textAlign: 'left',
    width: width - 70,
    alignSelf: 'center',
    paddingHorizontal: '10%',

    // marginTop: '1%',
  },
  senderMessage: {
    backgroundColor: '#ffff',
    color: 'grey',
    padding: '2%',
    borderWidth: 2,
    width: '60%',
    marginVertical: '1%',
    marginHorizontal: '1%',
    borderRadius: 10,
    fontSize: 16,
    fontFamily: 'Rubika',
    elevation: 5,
    // marginVertical: '1%',
    alignSelf: 'flex-start',
  },
  flatList: {
    backgroundColor: 'black',
    flex: 1,
  },
  reciverTime: {
    color: 'grey',
    fontSize: 10,
    marginBottom: '0.5%',
    marginHorizontal: '1.2%',
  },
  senderTime: {
    color: 'grey',
    fontSize: 10,
    marginBottom: '0.5%',
    marginHorizontal: '1.2%',
    alignSelf: 'flex-end',
  },
  senderImage: {
    // borderRadius: 10,
    alignSelf: 'flex-end',
    marginVertical: '3%',
    marginHorizontal: '2%',
    backgroundColor: 'transparent',
  },
  reciverImage: {
    backgroundColor: 'transparent',
    marginVertical: '2%',
    marginHorizontal: '2%',
  },
  conatinerChild: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'grey',
    // borderBottom: 1,
  },
  headerImage: {
    height: 60,
    width: 60,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'grey',
  },
  messageContainer: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    // backgroundColor: '#fff',
    // top: '-%',
    right: '6%',
    // position: 'absolute',
    // top: 300,
    marginVertical: '-4%',
  },
  inputContainer: {
    marginBottom: '2.7%',
    backgroundColor: '#fff',
    borderRadius: 20,

    // width: width - 60,
    marginHorizontal: '2%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: '6%',
    marginTop:"auto"
  },
  toolbar: {
    marginTop: 30,
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'red',
    height: 100,
    width: '40%',
  },
  mediaPlayer: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    height: 100,
    width: '40%',
    borderWidth: 1,
    borderColor: 'red',
  },
  currentUserMessage: {
    alignItems: 'flex-end',
    marginLeft: 50,
    marginTop: 10,
  },
  currentMessage: {
    backgroundColor: "#EA1B91",
    padding: 15,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderBottomLeftRadius: 15,
  },
  otherUserMessage: {
    marginTop: 10,
    marginRight: 50,
    alignItems: 'flex-start',
    flexWrap: 'wrap'
  },
  otherMessage: {
    backgroundColor: "#292929",
    padding: 15,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderBottomRightRadius: 15,
  },
});
