import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },

  textareaContainer: {
    height: 120,
    padding: 5,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 10,
  },
  textarea: {
    textAlignVertical: 'top', // hack android
    height: 120,
    fontSize: 16,

    color: '#fff',
  },

  nameInput: {
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 10,
    marginHorizontal: '3.4%',
    color: '#fff',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    backgroundColor: 'transparent',
    marginBottom: '2%',
    paddingVertical: '4%',
    paddingHorizontal: '4%',
  },
  phone: {
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 10,
    marginHorizontal: '3.4%',
    color: 'grey',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    backgroundColor: 'transparent',
    marginBottom: '2%',
  },
  ageInput: {
    borderColor: 'grey',
    borderWidth: 1,
    borderRadius: 10,
    height: 56,
    backgroundColor: 'black',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    // paddingVertical: '4%',
    paddingHorizontal: '6%',
    color: '#fff',
  },
  dropDown: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 10,
    height: 50,
  },

  startInput: {
    borderWidth: 1,
    borderColor: '#fff',
    color: '#fff',
    borderRadius: 4,
    padding: 2,
    backgroundColor: 'white',
    width: 160,
    height: 35,
    fontSize: 16,
  },

  dateListContainer: {
    marginHorizontal: '5%',
    borderColor: 'white',
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: '2%',
    borderRadius: 5,
    marginVertical: '2%',
  },
  nameList: {
    color: 'white',
  },
  dateList: {
    color: 'white',
  },
  detalsList: {
    color: '#3F6AED',
    textAlign: 'center',
  },
  moreDetails: {
    textAlign: 'center',
    paddingVertical: '2%',
  },
  header: {
    padding: '3%',
    color: 'white',
    backgroundColor: '#3F6AED',
    maxWidth: '35%',
    marginTop: '-0.6%',
    marginLeft: '-0.3%',
    fontWeight: 'bold',
    borderTopLeftRadius: 10,
    textAlign: 'center',
  },
  conatinerDate: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: '2%',
    marginBottom: '4%',
  },
  textInput: {
    backgroundColor: 'transparent',
    color: 'white',
    fontSize: 20,
    height: 30,
    marginTop: '16%',
    paddingTop: '26%',
  },
  heading: {color: 'white', fontSize: 16, textAlign: 'center'},
  dateContainer: {
    borderColor: 'grey',
    borderWidth: 1,
    marginHorizontal: '4%',
    marginVertical: '4%',
    borderRadius: 10,
  },
  phoneInput: {
    borderRadius: 10,

    marginTop: 0,
    marginBottom: 0,
    color: '#ffff',
    backgroundColor: 'black',
  },
  dropdownButtonStyle: {
    backgroundColor: 'black',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'grey',
    paddingRight: 0,
    paddingLeft: 0,
    marginHorizontal: '1%',
    marginBottom: '3%',
    height: 56,
  },
});
