import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    fontFamily: 'Rubik-Medium',
  },
  backH: {
    marginTop: 20,
    marginLeft: 10,
  },
  title: {
    fontSize: 18,
    marginTop: 3,
    width: '70%',
    textAlign: 'center',
    color: '#fff',
    fontFamily: 'Rubik',
  },
  caption: {
    fontSize: 10,
    textAlign: 'center',
    fontFamily: 'Rubik',
    color: '#fff',
  },

  linksInputs: {
    borderWidth: 1,
    borderColor: 'white',
    marginHorizontal: 15,
    borderRadius: 10,
    color: '#3F6AED',
    marginTop: 15,
    paddingVertical: '5%',
    fontFamily: 'Rubika-medium',
    paddingHorizontal: '2%',
  },
  icons: {
    backgroundColor: '#EA1B91',
    paddingLeft: 6,
    textAlign: 'center',
    borderRadius: 50,
    height: 50,
    width: 50,
    paddingTop: 14,
    paddingRight: 4,
    position: 'absolute',
    left: 80,
    top: 55,
  },
  personal: {
    color: 'grey',
    fontSize: 22,
    paddingTop: 40,
    fontWeight: 'bold',
    marginLeft: 6,
    paddingLeft: 15,
  },
  profilePics: {
    borderWidth: 1,
    height: 90,
    width: 90,
    borderRadius: 10,
    borderColor: 'grey',
    marginLeft: '10%',
  },
  conatinerItem: {
    marginTop: '1%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
});
