import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    fontFamily: 'Rubik-Medium',
  },

  ageInput: {
    backgroundColor: 'black',
    color: 'grey',
    textAlign: 'center',
  },
  ageI: {
    // backgroundColor: 'black',
    color: 'grey',
  },
  datePicker: {
    backgroundColor: 'black',
    marginTop: 10,
  },
  containerStyle: {
    marginHorizontal: 20,

    justifyContent: 'center',
    backgroundColor: 'black',
    paddingTop: 10,
  },
  drop: {
    backgroundColor: 'transparent',

    borderColor: 'red',
    borderWidth: 1,

    // fontSize: 32
  },
  education: {
    marginHorizontal: 20,

    justifyContent: 'center',
    backgroundColor: 'black',
    paddingTop: 2,
    marginBottom: 10,
    borderColor: 'red',
    // borderBottomWidth: 1,
    borderColor: 'grey',
  },
  educationInput: {
    backgroundColor: '#000000',
    borderColor: 'grey',
    borderBottomWidth: 1,
  },
  customText: {
    borderColor: 'grey',
  },
  textFocus: {
    borderColor: '#ffff',
  },
  dateValue: {color: '#fff', paddingTop: 0, paddingBottom: 0, fontSize: 18},
  ageYears: {
    color: 'grey',
    paddingTop: 0,
    paddingBottom: 0,
    fontSize: 18,
    alignSelf: 'flex-end',
    marginTop: -24,
    marginRight: 15,
  },
  kgText: {
    color: '#fff',
    fontSize: 18,
    marginBottom: 0,
    paddingVertical: '2%',
    paddingHorizontal: '2%',
  },
  sideLogo: {
    width: 60,
    height: 60,
    alignSelf: 'flex-end',
    marginTop: -50,
    marginRight: 10,
  },
  ageContainer: {
    height: 65,
    marginTop: -30,
    marginLeft: 20,
    marginRight: 20,
    // borderBottomWidth: 1,
    borderColor: '#ffff',
  },
  listConatiner: {color: 'grey', fontSize: 16, paddingTop: 3, marginBottom: 0},
  inputText: {
    color: 'white',
    backgroundColor: 'rgb(0,0,0)',
    borderColor: 'rgb(128,128,128)',
    // borderBottomWidth: 1,
    borderWidth: 1,

    marginVertical: '2%',
    paddingVertical: 10,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginHorizontal: '1%',
    textDecorationLine: 'none',
    height: 56,
  },
  heightInput: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    position: 'absolute',
    bottom: 18,
    right: 15,
  },
  weightInput: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    position: 'absolute',
    right: 26,
    bottom: 26,
  },
  heightIncrement: {
    backgroundColor: '#000000',
    borderRadius: 50,
    borderColor: 'grey',
    borderWidth: 1,
    height: 30,
    width: 30,
    paddingTop: 6,
    // paddingLeft: 12,
    justifyContent: 'center',
    // marginRight: '-3.5%',
    textAlign: 'center',
  },
  heightDecrement: {
    backgroundColor: '#000000',
    borderRadius: 50,
    borderColor: 'grey',
    borderWidth: 1,
    height: 30,
    width: 30,
    paddingTop: 5,
    // paddingLeft: 12,
    justifyContent: 'center',
    marginHorizontal: 10,
    // marginVertical: 20,
    textAlign: 'center',
  },
  weightIncremnt: {
    backgroundColor: '#000000',
    borderRadius: 50,
    borderColor: 'grey',
    borderWidth: 1,
    height: 30,
    width: 30,
    paddingTop: 5,
    // paddingLeft: 12,
    justifyContent: 'center',
    marginHorizontal: 10,
    textAlign: 'center',
  },
  weightDecrement: {
    backgroundColor: '#000000',
    borderRadius: 50,
    borderColor: 'grey',
    borderWidth: 1,
    height: 30,
    width: 30,
    paddingTop: 5,
    // paddingLeft: 12,
    justifyContent: 'center',
    marginHorizontal: 2,
    textAlign: 'center',
  },
  ageContainerOne: {
    marginTop: 35,
    marginLeft: 20,
    marginRight: 20,
    // borderBottomWidth: 1,
    // borderColor: '#ffff',
  },
  button: {
    marginHorizontal: '2%',
    marginBottom: '15%',
  },
  dateOf: {
    // backgroundColor: '#00000 ',
    borderWidth: 1,
    borderColor: 'grey',
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    maxHeight: 56,
    marginVertical: '2%',
  },
  heightInpu: {
    backgroundColor: 'black',
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 6,
    height: 54,
    marginLeft: '2%',
    marginRight: '2%',
    marginVertical: '2%',
  },
});
