version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_DB=Confidate
      - POSTGRES_USER=Confidate
      - POSTGRES_PASSWORD=Confidate

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
